### ISSUE TITLE
Not building on Mac

### ISSUE THREAD

**Issue by gandarez** [Tatsh/kate-wakatime#15]
Followed the instructions on Readme but couldn't build for Mac.

OS: macOS Mojave
cmake: 3.15.2

logs:
[output.log](https://github.com/Tatsh/kate-wakatime/files/3555436/output.log)
[CMakeOutput.log](https://github.com/Tatsh/kate-wakatime/files/3555437/CMakeOutput.log)

**Comment by gandarez** [comment]
To solve the initial problem I followed these instructions https://superuser.com/a/912259/180586

Then I got another error and had to install `qt` via homebrew and set its path. https://github.com/sijk/qt5-sqlcipher/issues/14#issuecomment-385221910

```
-- Could NOT find KF5TextEditor (missing: KF5TextEditor_DIR)
CMake Error at CMakeLists.txt:28 (find_package):
  By not providing "FindQt5Sql.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Qt5Sql", but
  CMake did not find one.

  Could not find a package configuration file provided by "Qt5Sql" with any
  of the following names:

    Qt5SqlConfig.cmake
    qt5sql-config.cmake

  Add the installation prefix of "Qt5Sql" to CMAKE_PREFIX_PATH or set
  "Qt5Sql_DIR" to a directory containing one of the above files.  If "Qt5Sql"
  provides a separate development package or SDK, be sure it has been
  installed.
```

Then got another error and 
```
-- Could NOT find KF5TextEditor (missing: KF5TextEditor_DIR)
CMake Error at CMakeLists.txt:34 (ki18n_wrap_ui):
  Unknown CMake command "ki18n_wrap_ui".
```

**Comment by Tatsh** [comment]
You need the package kde-extra-cmake-modules installed. I don't know if Homebrew has that.

**Comment by gandarez** [comment]
I already did that as I mentioned one post above. I need your help dude!

**Comment by Tatsh** [comment]
Then you need ktexteditor

**Comment by gandarez** [comment]
I did

```
brew install cpanminus
cpanm URI
"$(brew --repo kde-mac/kde)/tools/do-caveats.sh"
brew install kde-mac/kde/kf5-ktexteditor
```

Then I installed `GetText` via brew and set these variables in the beginning of `CMakeLists.txt`

```
set(Qt5Sql_DIR /usr/local/Cellar/qt/5.13.0/lib/cmake/Qt5Sql/)
set(Qt5Xml_DIR /usr/local/Cellar/qt/5.13.0/lib/cmake/Qt5Xml/)
set(Qt5Widgets_DIR /usr/local/Cellar/qt/5.13.0/lib/cmake/Qt5Widgets/)
set(Qt5DBus_DIR /usr/local/Cellar/qt/5.13.0/lib/cmake/Qt5DBus/)
set(Qt5Network_DIR /usr/local/Cellar/qt/5.13.0/lib/cmake/Qt5Network/)
set(Qt5Concurrent_DIR /usr/local/Cellar/qt/5.13.0/lib/cmake/Qt5Concurrent/)
```

Got the erro below
```
CMake Error at /usr/local/Cellar/cmake/3.15.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find Gettext (missing: GETTEXT_MSGMERGE_EXECUTABLE
  GETTEXT_MSGFMT_EXECUTABLE)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.15.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/Cellar/cmake/3.15.2/share/cmake/Modules/FindGettext.cmake:81 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  /usr/local/lib/cmake/KF5I18n/KF5I18nMacros.cmake:28 (find_package)
  /usr/local/lib/cmake/KF5I18n/KF5I18nConfig.cmake:33 (include)
  /usr/local/Cellar/cmake/3.15.2/share/cmake/Modules/CMakeFindDependencyMacro.cmake:47 (find_package)
  /usr/local/lib/cmake/KF5TextWidgets/KF5TextWidgetsConfig.cmake:30 (find_dependency)
  /usr/local/Cellar/cmake/3.15.2/share/cmake/Modules/CMakeFindDependencyMacro.cmake:47 (find_package)
  /usr/local/lib/cmake/KF5Parts/KF5PartsConfig.cmake:29 (find_dependency)
  /usr/local/lib/cmake/KF5TextEditor/KF5TextEditorConfig.cmake:28 (find_package)
  CMakeLists.txt:34 (find_package)
```

**Comment by Tatsh** [comment]
Looks like you need gettext

**Comment by Tatsh** [comment]
If it can't see gettext then there might be something else you have to install. Like a gettext development package.

**Comment by gandarez** [comment]
I added `gettext` to the `PATH`

```
export PATH=$PATH:/usr/local/opt/gettext/bin
```

Then I finally could compile with success. Following the instructions I couldn't find any `Extensions`  page and just found `Plugin Manager` which doesn't have any `WakaTime`.
<img width="906" alt="Screen Shot 2019-08-30 at 18 39 54" src="https://user-images.githubusercontent.com/782854/64052634-aad11a80-cb55-11e9-888e-e1bd09a2f08e.png">
<img width="521" alt="Screen Shot 2019-08-30 at 18 40 58" src="https://user-images.githubusercontent.com/782854/64052644-ba506380-cb55-11e9-9bf9-285bf3a8323b.png">

**Comment by Tatsh** [comment]
That prefix path when you run cmake originally has to be the path Homebrew uses which looks like it would be: /usr/local/opt

**Comment by Tatsh** [comment]
Isn't there a `brew --prefix` command or similar?

**Comment by gandarez** [comment]
`brew info` shows that ktexteditor is installed on the path `/usr/local/Cellar/kf5-ktexteditor/5.61.0`. Should I run cmake passing to `DCMAKE_INSTALL_PREFIX` argument this path?
<img width="443" alt="Screen Shot 2019-09-01 at 19 57 25" src="https://user-images.githubusercontent.com/782854/64083241-dccbb380-ccf2-11e9-8290-3b85d60a2299.png">

**Comment by Tatsh** [comment]
What's inside this path? bin? lib? Is there a plugins directory inside? If there is lib/plugins/ktexteditor inside, I would definitely try that.

**Comment by gandarez** [comment]
```
.
├── INSTALL_RECEIPT.json
├── README.md
├── include
│   └── KF5
├── install_manifest.txt
├── lib
│   ├── cmake
│   ├── libKF5TextEditor.5.61.0.dylib
│   ├── libKF5TextEditor.5.dylib -> libKF5TextEditor.5.61.0.dylib
│   ├── libKF5TextEditor.dylib -> libKF5TextEditor.5.dylib
│   ├── libexec
│   └── qt5
├── mkspecs
│   └── modules
└── share
    ├── dbus-1
    ├── doc
    ├── katepart5
    ├── kdevappwizard
    ├── kservices5
    ├── kservicetypes5
    ├── locale
    └── qlogging-categories5

17 directories, 6 files

```

**Comment by Tatsh** [comment]
Probably not the place. Can you run this and show output?

`find /usr/local/Cellar -type d -name plugins`

**Comment by gandarez** [comment]
```
/usr/local/Cellar/kf5-ki18n/5.61.0/lib/qt5/plugins
/usr/local/Cellar/kf5-kwindowsystem/5.61.0/lib/qt5/plugins
/usr/local/Cellar/kf5-kiconthemes/5.61.0/lib/qt5/plugins
/usr/local/Cellar/qt/5.13.0/plugins
/usr/local/Cellar/phonon/4.10.3/lib/qt5/plugins
/usr/local/Cellar/kf5-sonnet/5.61.0/lib/qt5/plugins
/usr/local/Cellar/kf5-ktexteditor/5.61.0/lib/qt5/plugins
/usr/local/Cellar/kf5-kauth/5.61.0/lib/qt5/plugins
/usr/local/Cellar/kf5-kio/5.61.0_1/lib/qt5/plugins
/usr/local/Cellar/cocoapods/1.7.5/libexec/gems/cocoapods-plugins-1.0.0/spec/command/plugins
/usr/local/Cellar/cocoapods/1.7.5/libexec/gems/cocoapods-plugins-1.0.0/lib/pod/command/plugins
```

**Comment by Tatsh** [comment]
Yes try setting the prefix to `/usr/local/Cellar/kf5-ktexteditor/5.61.0/`.

**Comment by gandarez** [comment]
Installed but can't see any `WakaTime` plugin in the screen I previous mentioned
<img width="732" alt="Screen Shot 2019-09-01 at 20 51 03" src="https://user-images.githubusercontent.com/782854/64083742-7d71a180-ccfa-11e9-9ab8-4cefead34820.png">

**Comment by Tatsh** [comment]
Fully restarted Kate?

**Comment by Tatsh** [comment]
Run sudo make uninstall and then try the qt plugins path instead.

**Comment by gandarez** [comment]
Do you mean `/usr/local/Cellar/kf5-ktexteditor/5.61.0/lib/qt5`?

**Comment by Tatsh** [comment]
Actually try placing the .so file installed in the same place as the other plugin so files under kf5-ktexteditor.

**Comment by gandarez** [comment]
It seems not to be working and there's just `ktexteditor` inside `plugin` folder. I can't see where're located the others as the 3rd image shows.
<img width="228" alt="Screen Shot 2019-09-02 at 14 12 46" src="https://user-images.githubusercontent.com/782854/64128226-d89fa480-cd8b-11e9-9f1a-9c70524f274e.png">
<img width="730" alt="Screen Shot 2019-09-02 at 14 11 38" src="https://user-images.githubusercontent.com/782854/64128230-df2e1c00-cd8b-11e9-890c-4a1ca6d74431.png">
<img width="905" alt="Screen Shot 2019-09-02 at 14 11 24" src="https://user-images.githubusercontent.com/782854/64128235-e48b6680-cd8b-11e9-9514-73e1056d5345.png">

**Comment by gandarez** [comment]
Finally I realized that the plugins folder is `/Applications/kate.app/Contents/PlugIns/ktexteditor` which holds all plugins for the editor. I just copied `ktexteditor_wakatime.so` from `/usr/local/Cellar/kf5-ktexteditor/5.61.0/lib/plugins/ktexteditor` to this folder. However when I click to enable WakaTime Kate closes unexpectedly. Do you know where I can find the logs?

**Comment by Tatsh** [comment]
It's probably not going to work from there but if it crashes you should open up Console.app and copy and paste the crash log here with ``` formatting (or attach a file).

**Comment by gandarez** [comment]
I have no idea how to open `Console.app`

**Comment by Tatsh** [comment]
Applications - Utilities - Console

**Comment by gandarez** [comment]
You mean the terminal, right. What should I do inside terminal?

**Comment by Tatsh** [comment]
There's an app called Console. It's not the same as Terminal.

<img width="948" alt="Console-2019-09-02 19-44-38" src="https://user-images.githubusercontent.com/724848/64135787-57133b00-cdba-11e9-9845-86d2894d3286.png">

Once you open it, go to Crash Reports and then find the one for Kate.

**Comment by gandarez** [comment]
Sorry I haven't heard about this tool before. I've attached the desired log.

[kate_2019-09-02-212113_Gandarezs-Macbook-Pro.log](https://github.com/Tatsh/kate-wakatime/files/3567310/kate_2019-09-02-212113_Gandarezs-Macbook-Pro.log)

**Comment by Tatsh** [comment]
Based on the crash report, it's crashing early in KDE's code right before it would ever load my plugin.

Note that it's not normal to place things inside an app bundle in macOS especially since if the bundle is signed this would invalidate the integrity checks.

You should file a bug with the maintainers of KF5 stuff for Homebrew and reference this issue. Ask them to make a formula for Kate-WakaTime.

Try deleting the .so file from the Kate.app bundle and try setting the `QT_PLUGIN_PATH` environment variable:

```sh
export QT_PLUGIN_PATH=/usr/local/Cellar/kf5-ktexteditor/5.61.0/lib/plugins
```

Then run Kate from the terminal: `/Applications/kate.app/Contents/MacOS/kate`. If this works, then it's not an issue with my plugin. You need to get the maintainers of the Homebrew formulae for KF5 to set this variable in the code, or some other way (another option is to bundle Kate-WakaTime in the Kate.app bundle if that would work).

I don't use Homebrew and cannot support you there. My main concern is my [Gentoo](https://github.com/Tatsh/tatsh-overlay/blob/master/kde-misc/kate-wakatime/kate-wakatime-1.3.3.ebuild) and [MacPorts](https://github.com/Tatsh/ports/blob/master/kf5/kf5-kate-wakatime/Portfile) packages for this project.

**Comment by gandarez** [comment]
exporting `QT_PLUGIN_PATH` and running `ktexteditor` from command line had the same behaviour as before. It's crashing when enabling `WakaTime`.
<img width="832" alt="Screen Shot 2019-09-03 at 08 52 47" src="https://user-images.githubusercontent.com/782854/64171172-5e712d80-ce28-11e9-94e2-babca5a3c8c9.png">

crash file: [kate_2019-09-03-085216_Gandarezs-Macbook-Pro.log](https://github.com/Tatsh/kate-wakatime/files/3569301/kate_2019-09-03-085216_Gandarezs-Macbook-Pro.log)

**Comment by Tatsh** [comment]
Did you delete the .so file in kate.app ? It should only be loading Kate-Wakatime from that plugins directory.

**Comment by Tatsh** [comment]
Those warnings you are getting should not be ignored. You should report those messages to the maintainers of the KF5 Homebrew formulae.

**Comment by gandarez** [comment]
> Did you delete the .so file in kate.app ? It should only be loading Kate-Wakatime from that plugins directory.

sure, deleted from `kate.app` and kept only at brew's installation folder.
