### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by englianhu** [Tatsh/kate-wakatime#16]
There has error when run to below part :
```r
:~/kate-wakatime/build$ cmake .. -DCMAKE_INSTALL_PREFIX=/usr
```
and then try to install
```r
:~$ ## https://superuser.com/a/912259/411834
:~$ git clone https://invent.kde.org/frameworks/extra-cmake-modules.git 
:~$ cd extra-cmake-modules
:~$ mkdir build && cd build    
:~$ cmake ..
:~$ make && sudo make install
:~$ 
:~$ ## https://wiki.qt.io/Install_Qt_5_on_Ubuntu
:~$ sudo apt-get install qt5-default
```
- [Could not find a configuration file for package `“ECM”` that is compatible with requested `version 1.5.0`](https://superuser.com/a/912259/411834)
- [Install `Qt 5` on Ubuntu](https://wiki.qt.io/Install_Qt_5_on_Ubuntu)

but then
```diff
+:~/kate-wakatime/build$ cmake .. -DCMAKE_INSTALL_PREFIX=/usr
Installing in /usr. Run /home/englianhu/kate-wakatime/build/prefix.sh to set the environment for ktexteditor_wakatime.
-- Could NOT find KF5TextEditor (missing: KF5TextEditor_DIR)
-CMake Error at CMakeLists.txt:32 (ki18n_wrap_ui):
-  Unknown CMake command "ki18n_wrap_ui".
```

**Comment by Tatsh** [comment]
`ki18n_wrap_ui` comes from a package that would provide `/usr/lib64/cmake/KF5I18n/KF5I18nMacros.cmake` (or similar path). On Gentoo that's the `kde-frameworks/ki18n` framework.

**Comment by angry-master-yoda** [comment]
The same. And I can't find this framework.

**Comment by derenv** [comment]
for anyone on fedora, this requires `kf5-ktexteditor-devel`.
