### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by TGelijah** [Tatsh/kate-wakatime#23]
During the Make process this happens
all dependencies are installed including extra-cmake-modules

`make`
[ 11%] Generating ktexteditor_wakatime.json
About to parse service type file "/usr/share/kservicetypes5/ktexteditorplugin.desktop"
Generated  "/home/user/kate-wakatime/build/ktexteditor_wakatime.json"
[ 22%] Automatic MOC for target ktexteditor_wakatime
[ 22%] Built target ktexteditor_wakatime_autogen
[ 33%] Generating ui_configdialog.h
[ 44%] Generating qrc_plugin.cpp
[ 55%] Building CXX object CMakeFiles/ktexteditor_wakatime.dir/ktexteditor_wakatime_autogen/mocs_compilation.cpp.o
[ 66%] Building CXX object CMakeFiles/ktexteditor_wakatime.dir/wakatimeplugin.cpp.o
/home/user/kate-wakatime/wakatimeplugin.cpp:36:10: fatal error: KF5/ktexteditor_version.h: No such file or directory
   36 | #include <KF5/ktexteditor_version.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/ktexteditor_wakatime.dir/build.make:100: CMakeFiles/ktexteditor_wakatime.dir/wakatimeplugin.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:732: CMakeFiles/ktexteditor_wakatime.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
`

**Comment by Tatsh** [comment]
Make sure you have development files for `ktexteditor`, which is a library not an app. I am on Gentoo.

I do not know what distro you are on but it should be [libkf5texteditor-dev](https://packages.ubuntu.com/bionic/libkf5texteditor-dev) on Ubuntu.

**Comment by TGelijah** [comment]
I am on Arch KDE, trying to find an arch equivalent of _libkf5texteditor-dev_ leads me back to the ktexteditor package which comes preinstalled with my DE. I will install the kde-dev tools and see if anything changes.

**Comment by RiedleroD** [comment]
changing the include from `KF5/ktexteditor_version.h` to `KF5/KTextEditor/ktexteditor_version.h` fixed it for me. the `kde-dev-utils` package wasn't relevant, the necessary file was in `ktexteditor`, as expected.

**Comment by hmmftg** [comment]
> Make sure you have development files for `ktexteditor`, which is a library not an app. I am on Gentoo.
> 
> I do not know what distro you are on but it should be [libkf5texteditor-dev](https://packages.ubuntu.com/bionic/libkf5texteditor-dev) on Ubuntu.

Hi, for ubuntu users use this command: `sudo apt-get install libkf5texteditor-dev`
