### ISSUE TITLE
missing dependency

### ISSUE THREAD

**Issue by RiedleroD** [Tatsh/kate-wakatime#25]
on arch linux at least, `extra-cmake-modules` is required to build this. Ofc `ktexteditor` as well, but that's already required by kate, and kate is an obvious one.

**Comment by Tatsh** [comment]
This isn't really actionable as written here. Do you want to update the readme and send a PR? The `CMakeLists.txt` [shows](https://github.com/Tatsh/kate-wakatime/blob/master/CMakeLists.txt#L7) `ECM` as required.

**Comment by RiedleroD** [comment]
interesting, because cmake worked just fine, only make took issue.
