### ISSUE TITLE
Offline support

### ISSUE THREAD

**Issue by Tatsh** [Tatsh/kate-wakatime#4]
Save a persistent queue until network connectivity is regained.

**Comment by Tatsh** [comment]
@alanhamlett I have created the variant you spoke of. It runs Wakatime (where `wakatime` must be in `PATH`; no Windows support).

I have not yet created a way to specify the location of `python` (Python 2 I presume), and a place to specify where the `wakatime` is. But mostly this is because on any *nix system `wakatime` can be in `PATH` and executed that way rather than having to prefix the `python`.

Needs more work, but I would appreciate your thoughts on the change. This is largely based on how the Xcode plugin works, but I am watching over the task that launches because I want to make sure never to have more than one `wakatime` process running.

**Comment by alanhamlett** [comment]
> I would still like to use the mode (language) as detected by Katepart as I think it is more accurate and less generic

I agree, it's best to use Kate's language detection and only use wakatime's language detection (via Pygments library) if Kate doesn't specify a language.
