### ISSUE TITLE
Make a dialog for configuration

### ISSUE THREAD

**Issue by Tatsh** [Tatsh/kate-wakatime#5]
Edits `~/.wakatime.cfg`.

**Comment by 0x70ad57001** [comment]
Why not have the plugin create an empty config file (with all configuration options and such blank) and as for the API key on first run or if no key exists, have a prompt and have the user enter their API key. Seems a little more simplistic than creating a whole dialog for such a thing unless more options are going to be implemented then perhaps an option dialog.

**Comment by Tatsh** [comment]
https://github.com/KDE/kate/blob/master/addons/textfilter/plugin_katetextfilter.cpp#L252
https://github.com/KDE/kate/blob/master/addons/textfilter/plugin_katetextfilter.cpp#L150
